config/routes.rb
Rails.application.routes.draw do
  root 'application#page_vide'
  devise_for :users
  resources :learners
  resources :groups
  resources :products
  resources :providers
  resources :tasks
  resources :lists do
    resources :tasks, :only => [:create, :new, :edit, :update]
  end
  get 'page_vide' => 'application#page_vide'
  put 'remove_group/:id' => 'learners#alonize', as: :alonize
  get 'random'  => "groups#rand_populate"
  get 'page_1' => 'static_pages#page_1'
  get 'page_2' => 'static_pages#page_2'
  get 'users' => 'users#index'
  get 'like' => 'likes#create'
  get "send_news" => "application#newsletter_send"
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks ,dependent: :destroy
  def dead_line_list(aa)
    if aa.future?
      t =  aa - Time.now

      mm, ss = t.divmod(60)            #=> [4515, 21]
      hh, mm = mm.divmod(60)           #=> [75, 15]
      dd, hh = hh.divmod(24)           #=> [3, 3]
      return "#{dd} days, #{hh} hours, #{mm} minutes and #{ss.round()} seconds"
    else
      return 'Dead!!'
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
    @list.user_id = current_user.id
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :description, :duration, :dead_line, :user_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= bootstrap_form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.text_field :name %>
    <%= f.text_area :description %>

    <%= f.datetime_select :dead_line %>

    <%= f.submit %>

<% end %>

app/views/lists/edit.html.erb
<% content_for :head do %>
  <title>Todo</title>
<% end %>
<% content_for :nav do %>
 <%= render partial: "navs/nav_links"%>
<% end %>
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<% content_for :head do %>
  <title>Listing Lists</title>
<% end %>
<% content_for :nav do %>
 <%= render partial: "navs/nav_links"%>
<% end %>
<h1>Todos</h1>
<h5>Red color when due date is past or sum of tasks duration and current time   is over Deadline</h5>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Duration</th>
      <th>Dead line</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <%total_h = list.tasks.each.map{|x| x.duration.hour}.sum%>
      <%total_m = list.tasks.each.map{|x| x.duration.min}.sum%>
      <%total_sec = list.tasks.each.map{|x| x.duration.sec}.sum %>
      <%a = Time.now.to_datetime%>
      <%a+= total_h.hour%>
      <% a+= total_m.minutes%>
      <%  a+= total_m.seconds%>
    <%color =  a < list.dead_line  ? "success" : "danger"%>
    <tr class=<%="#{color}"%>>
      <td><%= list.name %></td>
      <td><%= list.description %></td>
      <td><%= "Total: #{total_h}hours #{total_m} mins #{total_sec} secs" %></td>
      <td><%= list.dead_line_list(list.dead_line) %></td>
      <td><%= list.user.email %></td>
      <td><%= link_to 'Show', list %></td>
      <td><%= link_to 'ad a task', new_list_task_path(:list_id => list.id) %></td>
      <td><%= link_to 'Edit', edit_list_path(list) %></td>
      <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <%if list.tasks.count> 0%>
    <%list.tasks.each do |task|%>
    <%color = task.due_date.future? ? "success" : "danger"%>
    <tr class=<%="#{color}"%>>

      <td></td>
      <td><%= task.name %></td>
      <td><%= task.comment %></td>
      <td><%= "#{task.duration.hour}H#{task.duration.min}M#{task.duration.sec}" %></td>
      <td><%= task.dead_line(task.due_date) %></td>
      <td> <%=link_to 'Edit', edit_list_task_path(list, task) %></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <% end %>
    <% end %>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<% content_for :head do %>
  <title>Todo</title>
<% end %>
<% content_for :nav do %>
 <%= render partial: "navs/nav_links"%>
<% end %>
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<% content_for :head do %>
  <title>Todo</title>
<% end %>
<% content_for :nav do %>
 <%= render partial: "navs/nav_links"%>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @list.duration %>
</p>

<p>
  <strong>Dead line:</strong>
  <%= @list.dead_line %>
</p>

<p>
  <strong>User:</strong>
  <%= @list.user.email %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>