config/routes.rb
Rails.application.routes.draw do
  root 'application#page_vide'
  devise_for :users
  resources :learners
  resources :groups
  resources :products
  resources :providers
  resources :tasks
  resources :lists do
    resources :tasks, :only => [:create, :new, :edit, :update]
  end
  get 'page_vide' => 'application#page_vide'
  put 'remove_group/:id' => 'learners#alonize', as: :alonize
  get 'random'  => "groups#rand_populate"
  get 'page_1' => 'static_pages#page_1'
  get 'page_2' => 'static_pages#page_2'
  get 'users' => 'users#index'
  get 'like' => 'likes#create'
  get "send_news" => "application#newsletter_send"
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  def dead_line(aa)
    if aa.future?
      t =  aa - Time.now

      mm, ss = t.divmod(60)            #=> [4515, 21]
      hh, mm = mm.divmod(60)           #=> [75, 15]
      dd, hh = hh.divmod(24)           #=> [3, 3]
      return "#{dd} days, #{hh} hours, #{mm} minutes and #{ss.round()} seconds"
    else
      return 'Dead!!'
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_list, only: [:new, :edit]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.due_date = @list.dead_line
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    # @list = List.find(params[:list_id])
    @task = Task.new(task_params)
    @task.list_id = params[:list_id]
    respond_to do |format|
      if @task.save
        format.html { redirect_to lists_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to lists_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to list_tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end
    def set_list
      @list = List.find(params[:list_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :comment, :duration, :due_date, :list_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= bootstrap_form_for([@list , @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name %>
    <%= f.datetime_select :due_date %>
    <%= f.time_select :duration %>
    <%= f.text_field :comment %>
    <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th>Duration</th>
      <th>Due date</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>

      <tr>
        <td><%= task.name %></td>
        <td><%= task.comment %></td>
        <td><%= task.duration %></td>
        <td><%= task.dead_line(task.due_date) %></td>
        <td><%= task.list.name unless task.list.nil? %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @task.comment %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task.duration %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>List:</strong>
  <%= @task.list %>
</p>

<%= link_to 'Edit', edit_list_task_path(params[:list_id] = @task.list, @task) %> |
<%= link_to 'Back', tasks_path %>