config/routes.rb
Rails.application.routes.draw do
  root 'application#page_vide'
  devise_for :users
  resources :learners
  resources :groups
  resources :products
  resources :providers
  resources :tasks
  resources :lists do
    resources :tasks, :only => [:create, :new, :edit, :update]
  end
  get 'page_vide' => 'application#page_vide'
  put 'remove_group/:id' => 'learners#alonize', as: :alonize
  get 'random'  => "groups#rand_populate"
  get 'page_1' => 'static_pages#page_1'
  get 'page_2' => 'static_pages#page_2'
  get 'users' => 'users#index'
  get 'like' => 'likes#create'
  get "send_news" => "application#newsletter_send"
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  validates_uniqueness_of :user_id, scope: :product_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to products_path ,notice: "Yeahh, We liked it too!!!" }
        format.js {}
        format.json { render :show, status: :created, location: @like }
      else

        format.js {}
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_like
    @like = Like.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def like_params
    redirect_to :root if params[:user_id] != current_user.id.to_s
    params.permit(:user_id, :product_id)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/_like_button.html.erb
 <div  class="btn-group col-xs-12">
                <span><%= link_to 'Show', product ,class: "btn btn-default" %></span>
                <% if product.likes.where(user_id: user).exists? %>
                <span id='<%=product.id%>' class="btn btn-primary">
                    LIKED!!!
                </span>
                <%else%>
                <span id='<%=product.id%>' >
                    <%= link_to 'like', like_path( user_id: current_user,product_id: product.id ),class: "btn btn-default", remote:  true %>
                </span>
                <% end %>
                
                <span><%= link_to 'Edit', edit_product_path(product) ,class: "btn btn-default"%></span>
                <span><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-default"%></span>
            </div>

app/views/likes/create.js.erb
var jojo = '<%= params[:product_id].to_s %>' ;
document.getElementById(jojo).innerHTML =  "LIKED!!!"
document.getElementById(jojo).className += 'btn btn-primary';

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Likes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.user %></td>
        <td><%= like.product %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @like.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @like.product %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>