config/routes.rb
Rails.application.routes.draw do
  root 'application#page_vide'
  devise_for :users
  resources :learners
  resources :groups
  resources :products
  resources :providers
  resources :tasks
  resources :lists do
    resources :tasks, :only => [:create, :new, :edit, :update]
  end
  get 'page_vide' => 'application#page_vide'
  put 'remove_group/:id' => 'learners#alonize', as: :alonize
  get 'random'  => "groups#rand_populate"
  get 'page_1' => 'static_pages#page_1'
  get 'page_2' => 'static_pages#page_2'
  get 'users' => 'users#index'
  get 'like' => 'likes#create'
  get "send_news" => "application#newsletter_send"
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :learners 
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end
  def rand_populate 
    if user_signed_in? && Group.count > 0
      learn_ids = []
      Learner.all.each{|x| learn_ids << x.id} 
      while learn_ids.count > 0
        Group.all.each do |grp|
          a = learn_ids.sample
          learn_ids.delete(a)
          Learner.find(a).update_attributes(group_id: grp.id)  unless a.nil?
        end
      end
    else
      redirect_to :root , notice: "Something is missing , authetification and/or at least one group "
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :index, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.learners.each {|x| x.update_attributes(group_id: nil, role: 0)}
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name, :room, :task)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>
  </div>
  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<% content_for :head do %>
  <title>Groupes</title>
<% end %>
<% content_for :nav do %>
 <%= render partial: "navs/nav_group"%>
<% end %>
<div class="group col-xs-12">
<div id="side_brand"class="col-xs-1">
  S<br/>
  I<br/>
  M<br/>
  P<br/>
  L<br/>
  O<br/>
  N<br/>
</div>
  <div class=" col-xs-10">
<div id="group">
<% @groups.each do |group| %>
<div class="col-xs-3 panel panel-primary">
  <div class="panel-heading">
    <div class="title"><%=group.name %>
    <div class=" pull-right"> <%= group.room %></div></div>
  </div>
  <div class="panel-body">
    
    <div class="title"> <%= group.task %></div>
    <% group.learners.sort_by { |h| h[:role] }.reverse.each do |stud| %>
    <div class="col-xs-12 well well-sm">
    <div id="stud" class="pull-left h2"><%= stud.name%><%if user_signed_in?%>
  <%= best_in_place stud, :role , :as => :select, :collection => {"0" => " ✓" ,"1"=> " Sensei"} %>

    <%else%>
    <%= stud.role == 0 ? " ✓" :  " Sensei" %>
    <% end %>
    </div>
    <div class="pull-right"><%= link_to "X" , alonize_path(stud),method: :put, remote: true, class: "btn btn-danger" %></div>

    </div>
    <% end %>
      <% if user_signed_in?%>  
    <div class="col-xs-12"><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs btn-block" %></div>
      <% end %>
  </div>
</div>
<% end %>

<div id="alone">
  <%Learner.group_less.each do |alone|%>
    <div class="panel panel-info col-xs-12">
      <div class="text-left h2">
        <%= alone.name%>
      </div>
       <div class="h1">
       <span>
       Put me in :   
       </span>
       <span>
         <%= best_in_place_if user_signed_in? , alone, :group_id, :as => :select, :collection => @groups.all.map {|s| [s.id, s.name]} %>
       </span>
      </div>     
      <% if user_signed_in?%>  
      <div class="pull-right h4">
        <%= link_to "Delete" , alone, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-block"  %>
      </div>
      <% end %>
    </div>
<% end %>
</div
</div>
 <% if user_signed_in?%>  
<button   class=" panel panel-primary panel-heading glyphicon glyphicon-plus" data-toggle="modal" data-target="#myModal" style=" font-size:50px; font-weight:bolder;">
</button>
<button   class=" panel panel-primary panel-heading glyphicon glyphicon-user" data-toggle="modal" data-target="#new_simplonian" style=" font-size:50px; font-weight:bolder;">
</button>
<%end%>
<%= link_to '' , random_path,class: 'panel panel-primary panel-heading glyphicon glyphicon-retweet',style:" font-size:60px; font-weight:bolder;" ,remote: :true %>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Group</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@group= Group.new) do |f| %>
          <% if @group.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
              <ul>
              <% @group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :room %><br>
            <%= f.text_field :room %>
          </div>
          <div class="field">
            <%= f.label :task %><br>
            <%= f.text_field :task %>
          </div>
          <div class="actions">
            <%= f.submit  class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="new_simplonian" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Simplonian</h4>
      </div>
      <div class="modal-body">
<%= form_for(@learner = Learner.new) do |f| %>
  <% if @learner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@learner.errors.count, "error") %> prohibited this learner from being saved:</h2>

      <ul>
      <% @learner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
      </div>
    </div>
  </div>
</div>

</div>

</div>
      <% content_for :foot do %>
<% end %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @group.room %>
</p>

<p>
  <strong>Task:</strong>
  <%= @group.task %>
</p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>